### ISSUE TITLE
Some WaitSynchN tests fail on newer firmware versions

### ISSUE THREAD

**Issue by bunnei** [citra-emu/hwtests#25]
I originally wrote the WaitSynchN tests to pass on my f/w 4.4 3DS XL. Apparently, some behavior in the OS changed, and some tests fail on f/w 6.x and newer:

<pre>SUCCESS: [Kernel::Ports] ConnectToPort
SUCCESS: [Test_WaitSynchN_00] Test_WaitSynchN_00
SUCCESS: [Test_WaitSynchN_01] Test_WaitSynchN_01
SUCCESS: [Test_WaitSynchN_02] Test_WaitSynchN_02
SUCCESS: [Test_WaitSynchN_03] Test_WaitSynchN_03
SUCCESS: [Test_WaitSynchN_04] Test_WaitSynchN_04
SUCCESS: [Test_WaitSynchN_05] Test_WaitSynchN_05
SOFTASSERT FAILURE: `output == 0`
    At `bool Kernel::WaitSynch::Test_WaitSynchN_06()` L224
FAILURE: [Test_WaitSynchN_06] Test_WaitSynchN_06
SUCCESS: [Test_WaitSynchN_07] Test_WaitSynchN_07
SUCCESS: [Test_WaitSynchN_08] Test_WaitSynchN_08
SUCCESS: [Test_WaitSynchN_09] Test_WaitSynchN_09
SUCCESS: [Test_WaitSynchN_10] Test_WaitSynchN_10
SUCCESS: [Test_WaitSynchN_11] Test_WaitSynchN_11
SUCCESS: [Test_WaitSynchN_12] Test_WaitSynchN_12
SOFTASSERT FAILURE: `output == 0`
    At `bool Kernel::WaitSynch::Test_WaitSynchN_13()` L377
FAILURE: [Test_WaitSynchN_13] Test_WaitSynchN_13
SOFTASSERT FAILURE: `output == 0`
    At `bool Kernel::WaitSynch::Test_WaitSynchN_14()` L390
FAILURE: [Test_WaitSynchN_14] Test_WaitSynchN_14
SUCCESS: [Test_WaitSynchN_15] Test_WaitSynchN_15
SOFTASSERT FAILURE: `output == 0`
    At `bool Kernel::WaitSynch::Test_WaitSynchN_16()` L440
FAILURE: [Test_WaitSynchN_16] Test_WaitSynchN_16
SUCCESS: [Test_WaitSynchN_17] Test_WaitSynchN_17
SUCCESS: [Test_WaitSynchN_18] Test_WaitSynchN_18
SUCCESS: [Test_WaitSynchN_19] Test_WaitSynchN_19
SUCCESS: [Test_WaitSynchN_20] Test_WaitSynchN_20
SUCCESS: [Test_WaitSynchN_21] Test_WaitSynchN_21
SUCCESS: [Test_WaitSynchN_22] Test_WaitSynchN_22
SUCCESS: [Test_WaitSynchN_23] Test_WaitSynchN_23
SUCCESS: [Test_WaitSynchN_24] Test_WaitSynchN_24
SUCCESS: [Test_WaitSynchN_25] Test_WaitSynchN_25
SUCCESS: [Test_WaitSynch1_00] Test_WaitSynch1_00
SUCCESS: [Test_WaitSynch1_01] Test_WaitSynch1_01
SUCCESS: [Test_WaitSynch1_02] Test_WaitSynch1_02
SUCCESS: [Test_WaitSynch1_03] Test_WaitSynch1_03
SUCCESS: [Test_WaitSynch1_04] Test_WaitSynch1_04
SUCCESS: [Test_WaitSynch1_05] Test_WaitSynch1_05
SUCCESS: [Test_WaitSynch1_06] Test_WaitSynch1_06
SUCCESS: [Test_WaitSynch1_07] Test_WaitSynch1_07
SUCCESS: [Test_WaitSynch_KernelType_Session] Test_WaitSynch_KernelType_Session
SUCCESS: [Test_WaitSynch_KernelType_SharedMem] Test_WaitSynch_KernelType_SharedMem
SUCCESS: [Test_WaitSynch_KernelType_AddressArbiter] Test_WaitSynch_KernelType_AddressArbiter</re>

**Comment by Subv** [comment]
I've run them in 9.2 and 11.2 and all of them pass. I'm closing this one.
